name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10.11", "3.11.3"]
    steps:
    - uses: actions/checkout@v3
    - name: Configura o Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Instala os requisitos do módulo
      run: |
        python -m pip install -r dev-requirements.txt
    - name: Executa os testes do pacote
      run: |
        python -m pytest --cov-report=xml --cov=inewave tests/
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        files: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-inewave
        fail_ci_if_error: true 
        verbose: true 
    - name: Veriricações de qualidade de código - tipagem estática
      run: |
        python -m mypy ./inewave
    - name: Verificações de qualidade de código - linter PEP8
      run: |
        python -m pylama --ignore E203 ./inewave
